/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sockets.Replicador;
import sucursalapp.*;

/**
 * Clase que permite la visualizacion de los inventarios
 *
 * @author Diego Alienware
 */
public class GestionInventario extends javax.swing.JFrame {

    /**
     * Creates new form GestionProducto
     */
    int selected = -1;
    private String archivo = "inventarioProductos.xml";
    private String producto;
    private String sucursal;

    /**
     * Creates new form GestionInventario
     */
    public GestionInventario() {
        initComponents();
        XMLInventario xml = new XMLInventario(sucursal);
        xml.listarInventario(this, archivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        gestor = new javax.swing.JTable();
        jBActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        gestor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Costo", "Cantidad", "Estado", "Imagen"
            }
        ));
        jScrollPane1.setViewportView(gestor);

        jScrollPane1.setBounds(90, 120, 420, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBActualizar.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        jBActualizar.setBounds(210, 270, 170, 60);
        jLayeredPane1.add(jBActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrinho supermercado.png"))); // NOI18N
        jLabel1.setBounds(330, 0, 90, 100);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Inventario SuperMercados XYZ");
        jLabel2.setBounds(50, 60, 270, 24);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos-verdes.jpg"))); // NOI18N
        jLabel3.setBounds(-5, 0, 600, 370);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        int selectedRow = this.gestor.getSelectedRow();
        if (selectedRow != -1) {
            String producto = (String) this.gestor.getModel().getValueAt(selectedRow, 0);
            String cantidad = (String) this.gestor.getModel().getValueAt(selectedRow, 3);
            System.out.println(SucursalApp.nombresucursal);
            XMLInventario xml = new XMLInventario(SucursalApp.nombresucursal);
            xml.actualizarInventario(SucursalApp.nombresucursal, producto, cantidad);

            if (SucursalApp.coordinador.equals("si")) {
            } else {
                XMLNodoCoordinador nodoCoord = new XMLNodoCoordinador();
                Nodo coordinador = nodoCoord.getCoordinador();
                Replicador replicador = new Replicador(SucursalApp.nombresucursal + ".xml", "10000", coordinador.getIp());
                new Thread(replicador).start();
            }

        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInventario().setVisible(true);
            }
        });
    }

    public void agregarfila(String nombre, String descripcion, String costo, String cantidad, String status, String imagen) {
        ((DefaultTableModel) this.gestor.getModel()).addRow(new Object[]{nombre, descripcion, costo, cantidad, status, imagen});
    }

    public ArrayList<String> getInventario() {
        ArrayList<String> inventario = new ArrayList<String>();
        for (int i = 0; i < this.gestor.getRowCount(); i++) {
            inventario.add((String) this.gestor.getModel().getValueAt(i, 0));
        }
        return inventario;
    }

    public Inventario getProductoInventarioSeleccionado() {
        int selectedRow = this.gestor.getSelectedRow();
        String productoNombre = (String) this.gestor.getModel().getValueAt(selectedRow, 0);
        String productoDesc = (String) this.gestor.getModel().getValueAt(selectedRow, 1);
        String productoCosto = (String) this.gestor.getModel().getValueAt(selectedRow, 2);
        String productoCantidad = (String) this.gestor.getModel().getValueAt(selectedRow, 3);
        //String productoStatus = (String) this.gestor.getModel().getValueAt(selectedRow, 4);

        Inventario inven = new Inventario(productoNombre, productoDesc, productoCosto, productoCantidad);
        return inven;
    }

    public int getRowCount() {
        return gestor.getRowCount();
    }

    private void gestorMouseClicked(java.awt.event.MouseEvent evt) {
        this.selected = gestor.getSelectedRow();
        System.out.print(selected);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gestor;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
